### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by chkaos** [LSivan/fmt_directory#1]
你好， 请教一下 这个和命令 go fmt ./... 比有什么优势吗?
Here ./ tells to start from the current folder, ... tells to go down recursively.

**Comment by LSivan** [comment]
> 你好， 请教一下 这个和命令 go fmt ./... 比有什么优势吗?
> Here ./ tells to start from the current folder, ... tells to go down recursively.

一年前了吧，当时我用的是gofmt，记得是gofmt会连vendor下的文件也格式化，所以不符合预期才写了这个工具
现在看了下好像vendor已经不会被format了

然后go fmt ./.. 之前没用过，我试了下发现这个命令会报错呀

**总结：这个工具是个不会format vendor 的go fmt 工具，没啥大优势😂**

**Comment by chkaos** [comment]
谢谢
